-- ut_objects_references

CREATE TABLE NGRULIER2.UT_OBJECT_REFERENTIAL FOR SYSTEM NAME UTREFOBJ ( 
	"ID" BIGINT NOT NULL DEFAULT 0 , 
	TEST_NAME VARCHAR(64) CCSID 273 NOT NULL DEFAULT '' , 
	TEST_DESCRIPTION FOR COLUMN TEST_00001 VARCHAR(500) CCSID 273 NOT NULL DEFAULT '' , 
	OBJECT_NAME FOR COLUMN OBJ_NAME   CHAR(10) CCSID 273 NOT NULL DEFAULT '' , 
	OBJECT_TYPE FOR COLUMN OBJ_TYPE   CHAR(10) CCSID 273 NOT NULL DEFAULT '' , 
	OBJECT_LIBRARY FOR COLUMN OBJ_LIB    CHAR(10) CCSID 273 NOT NULL DEFAULT '*LIBL' , 
	CONSTRAINT NGRULIER2.Q_NGRULIER1_UTREFOBJ_ID_00001 PRIMARY KEY( "ID" ) )   
	  
	RCDFMT UTREFOBJ   ; 
  
LABEL ON TABLE NGRULIER2.UT_OBJECT_REFERENTIAL 
	IS 'Unit test object referential' ; 
  
LABEL ON COLUMN NGRULIER2.UT_OBJECT_REFERENTIAL 
( "ID" TEXT IS 'id' , 
	TEST_NAME TEXT IS 'name of the unit test' , 
	TEST_DESCRIPTION TEXT IS 'Description' , 
	OBJECT_NAME TEXT IS 'name of the object tested' , 
	OBJECT_TYPE TEXT IS 'type of the tested object' ) ; 